import sqlite3
conn = sqlite3.connect('ecotrade.db')
cur = conn.cursor()
cur.execute("UPDATE hotels SET green_score=100 WHERE hotel_name='Gorilla Hills Resort'")
print('Updated rows:', cur.rowcount)
cur.execute("SELECT id, hotel_name, green_score FROM hotels WHERE hotel_name='Gorilla Hills Resort'")
print(cur.fetchone())
conn.commit()
conn.close()
print('Done.')
