"""add tin_number to hotel and recycler, rdb_certificate to documenttype

Revision ID: 06b1b1cce3cd
Revises: 
Create Date: 2026-03-19 12:30:30.284890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b1b1cce3cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_recycling_events_id'), table_name='recycling_events')
    op.drop_table('recycling_events')
    op.drop_index(op.f('ix_ticket_responses_id'), table_name='ticket_responses')
    op.drop_table('ticket_responses')
    op.add_column('hotels', sa.Column('tin_number', sa.String(length=100), nullable=True))
    op.add_column('recyclers', sa.Column('tin_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recyclers', 'tin_number')
    op.drop_column('hotels', 'tin_number')
    op.create_table('ticket_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_responses_id'), 'ticket_responses', ['id'], unique=False)
    op.create_table('recycling_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('waste_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recycling_events_id'), 'recycling_events', ['id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'"), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
